# Generated by Django 4.2.1 on 2023-09-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrefour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "site_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "categorie_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lien_categorie1_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "categorie_1_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lien_categorie2_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "categorie_2_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lien_categorie3_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "categorie_3_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nom_produit_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lien_produit_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_produit_carrefour",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "prix_produit_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "marque_produit_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("combined_dataset2", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Founa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("site_founa", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "categorie_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lien_categorie_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "categorie_1_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lien_categorie1_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "categorie_2_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "categorie_3_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lien_produit_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nom_produit_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description_produit_founa", models.TextField(blank=True, null=True)),
                (
                    "prix_produit_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prix_produit_avant_promos_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "promo_produit_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "poids_quantite_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reference_produit_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vendu_par_mg_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("combined_dataset3", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Monoprix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_article",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "libelle_article",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rayon", models.CharField(blank=True, max_length=255, null=True)),
                ("famille", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sous_famille",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("categorie", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sous_categorie",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("combined", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "similar_product_in_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prix_produit_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_produit_carrefour",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "similar_product_in_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prix_produit_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prix_produit_avant_promos_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description_produit_founa", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_article",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "similar_product_in_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prix_produit_carrefour",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_produit_carrefour",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "similar_product_in_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prix_produit_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prix_produit_avant_promos_founa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description_produit_founa", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
